CompileFlags:
  Add: [-Wall, -Wextras, -Winline, -Wno-unused-function, -pedantic]
Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - cert-*
      - concurrency-*
      - modernize-*
      - mpi-*
      - performance-*
    Remove:
      - bugprone-reserved-identifier
      - bugprone-easily-swappable-parameters
      - cert-dcl37-c
      - cert-dcl51-cpp
    FastCheckFilter: Strict
Hover:
  ShowAKA: true
